apiVersion: apps/v1
kind: Deployment
metadata:
  name:  identity
  namespace: safe-shop
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - image: safeshop/identity:master
          name: safeshop-identity
          imagePullPolicy: Always
          env:
            # .NET Core
          - name: PATH_BASE
            value: "/identity"

          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:80"

          resources:
            requests:
              memory: "256Mi"
              cpu: "256m"
            limits:
              memory: "512Mi"
              cpu: "512m"