version: '3.3'

services:
  identity.api:
    image: safeshop/identity:master
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PATH_BASE=/identity