version: '3'

services:
  catalog-import: 
    image: ghcr.io/safe-eshop/catalog.import:master
    environment:
      MONGODB_URL: "mongodb://catalogdb:27017"
      RABBITMQ_CONNECTION: "amqp://guest:guest@rabbitmq:5672/"
    depends_on: 
      - rabbitmq
      - catalogdb  
  catalog:
    image: ghcr.io/safe-eshop/catalog:master
    environment:
      MONGODB_URL: "mongodb://catalogdb:27017"
    depends_on: 
      - catalogdb
  warehouse:
    image: ghcr.io/safe-eshop/warehouse:master
    environment:
      REDIS_CONNECTION: "warehousedb:6380"
      RABBITMQ_CONNECTION: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - catalog
      - rabbitmq
      - warehousedb
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - '5672:5672'
      - '15672:15672'
  catalogdb:
    image: mongo:latest
    restart: unless-stopped
    ports: 
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
  warehousedb: 
    image: redis:alpine
    ports:
      - '6380:6379'

volumes:
  mongodb-data:
