apiVersion: apps/v1
kind: Deployment
metadata:
  name:  identity
  namespace: safe-shop
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - image: safeshop/identity:master
          name: safeshop-identity
          imagePullPolicy: Always
          env:
            # .NET Core
          - name: PATH_BASE
            value: "/identity"

          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:80"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "64m"
            limits:
              memory: "256Mi"
              cpu: "128m"